-- adding users

INSERT INTO PWEB.USERS (USERNAME, PASSWORD, EMAIL, AVATAR, ISMODERATOR, DATE_LOGIN) VALUES ('sec', 'exterminate', 'sec@cos.dk', 'default.png', true, CURRENT_TIMESTAMP);
INSERT INTO PWEB.USERS (USERNAME, PASSWORD, EMAIL, AVATAR, ISMODERATOR, DATE_LOGIN) VALUES ('davros', 'dalek', 'davros@skaro.tw', 'default.png', true, CURRENT_TIMESTAMP);
INSERT INTO PWEB.USERS (USERNAME, PASSWORD, EMAIL, AVATAR, ISMODERATOR, DATE_LOGIN) VALUES ('boxxy', 'yousee', 'imboxxy@you.see', 'default.png', true, CURRENT_TIMESTAMP);
INSERT INTO PWEB.USERS (USERNAME, PASSWORD, EMAIL, AVATAR, ISMODERATOR, DATE_LOGIN) VALUES ('paolo', 'rossi', 'paolossi@msn.it', 'default.png', false, CURRENT_TIMESTAMP);
INSERT INTO PWEB.USERS (USERNAME, PASSWORD, EMAIL, AVATAR, ISMODERATOR, DATE_LOGIN) VALUES ('jast', 'rotcod', 'jast@cos.dk', 'default.png', false, CURRENT_TIMESTAMP);
INSERT INTO PWEB.USERS (USERNAME, PASSWORD, EMAIL, AVATAR, ISMODERATOR, DATE_LOGIN) VALUES ('caan', 'timewar', 'caan@cos.dk', 'default.png', false, CURRENT_TIMESTAMP);
INSERT INTO PWEB.USERS (USERNAME, PASSWORD, EMAIL, AVATAR, ISMODERATOR, DATE_LOGIN) VALUES ('marco', 'polo', 'aoempolo@virgilio.it', 'default.png', false, CURRENT_TIMESTAMP);

-- adding groups

INSERT INTO PWEB.GROUPS ("NAME", ACTIVE, IS_PUBLIC, ID_OWNER, LAST_ACTIVITY) VALUES ('Cult of Skaro', false, true, 1,CURRENT_TIMESTAMP);
INSERT INTO PWEB.GROUPS ("NAME", ACTIVE, IS_PUBLIC, ID_OWNER, LAST_ACTIVITY) VALUES ('Supreme beings', true, true, 2,CURRENT_TIMESTAMP);
INSERT INTO PWEB.GROUPS ("NAME", ACTIVE, IS_PUBLIC, ID_OWNER, LAST_ACTIVITY) VALUES ('Sphere', true, false, 3, CURRENT_TIMESTAMP);

-- adding people to groups

INSERT INTO PWEB.GROUPUSER (ID_GROUP, ID_USER, ACTIVE) VALUES (1, 1, true);
INSERT INTO PWEB.GROUPUSER (ID_GROUP, ID_USER, ACTIVE) VALUES (2, 2, true);
INSERT INTO PWEB.GROUPUSER (ID_GROUP, ID_USER, ACTIVE) VALUES (3, 3, true);

-- adding invites

INSERT INTO PWEB.INVITE (ID_GROUP, ID_USER, INVITE_DATE, VISIBLE) VALUES (1, 5, '2013-11-10', true);
INSERT INTO PWEB.INVITE (ID_GROUP, ID_USER, INVITE_DATE, VISIBLE) VALUES (2, 1, '2013-11-12', true);
INSERT INTO PWEB.INVITE (ID_GROUP, ID_USER, INVITE_DATE, VISIBLE) VALUES (2, 5, '2013-11-12', true);
INSERT INTO PWEB.INVITE (ID_GROUP, ID_USER, INVITE_DATE, VISIBLE) VALUES (3, 4, '2013-11-13', true);

-- adding posts

INSERT INTO PWEB.POST (VISIBLE, DATE_POST, MESSAGE, ID_GROUP, ID_USER) VALUES (DEFAULT, CURRENT_TIMESTAMP, 'We must exterminate the doctor!!', 1, 1);
INSERT INTO PWEB.POST (VISIBLE, DATE_POST, MESSAGE, ID_GROUP, ID_USER) VALUES (DEFAULT, CURRENT_TIMESTAMP, 'I obey. Exterminate!', 1, 6);
INSERT INTO PWEB.POST (VISIBLE, DATE_POST, MESSAGE, ID_GROUP, ID_USER) VALUES (DEFAULT, CURRENT_TIMESTAMP, 'Ohai! I''m Boxxy, you see?',3, 3);
